<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xsl.xsl"?>

<!DOCTYPE Persons [
   <!ELEMENT Persons (Person)>
   <!ELEMENT Person (Name, Gender, Website, Email, DateOfBirth, Education, InformalEducation, Awards, Memberships, Interests, Jobs )>
   <!ATTLIST Person person_id CDATA #REQUIRED>
   <!ELEMENT Name (#PCDATA)>
   <!ELEMENT Gender (#PCDATA)>
   <!ELEMENT Website (#PCDATA)>
   <!ELEMENT Email (#PCDATA)>
   <!ELEMENT DateOfBirth (#PCDATA)>
   <!ELEMENT Education (FormStudy+ )>
   <!ELEMENT InformalEducation (Course+)>
   <!ELEMENT Jobs (Job+)>
   <!ELEMENT Awards (Award+)>
   <!ELEMENT Memberships (Membership+)>
   <!ELEMENT Interests (Interest+)>
   <!ELEMENT FormStudy (Name, City, GraduationYear, Subjects )>
   <!ATTLIST FormStudy education_id CDATA #REQUIRED>  
   <!ELEMENT Course (Name, YearGraduation)>
   <!ELEMENT Job (Title, JobDescription, JobPeriod)>
   <!ELEMENT Award (Name, TitleAward, YearAward)>
   <!ELEMENT Membership (Title, MembershipDescription, MembershipPeriod)>
   <!ELEMENT Interest (#PCDATA)>
   <!ELEMENT City (#PCDATA)>
   <!ELEMENT GraduationYear (#PCDATA)>
   <!ELEMENT Subjects (Subject+)>
   <!ELEMENT YearGraduation (#PCDATA)>
   <!ELEMENT Title (#PCDATA)>
   <!ELEMENT JobDescription (#PCDATA)>
   <!ELEMENT JobPeriod (#PCDATA)>
   <!ELEMENT TitleAward (#PCDATA)>
   <!ELEMENT YearAward (#PCDATA)>
   <!ELEMENT MembershipDescription (#PCDATA)>
   <!ELEMENT MembershipPeriod (#PCDATA)>
   <!ELEMENT Subject (Name, FinalGrade, Keyword, Year, SubjectType)>
   <!ELEMENT FinalGrade (#PCDATA)>
   <!ELEMENT Keyword (#PCDATA)>
   <!ELEMENT Year (#PCDATA)>
   <!ELEMENT SubjectType (#PCDATA)>
]>

<Persons>
  <Person person_id="1">
    <Name>Buzz Mcall</Name>
    <Gender>male</Gender>
    <Website>buzz.com</Website>
    <Email>buzz@yahoo.com</Email>
    <DateOfBirth>1990-02-14</DateOfBirth>
    <Education>
      <FormStudy education_id="0">
        <Name>Queens High School</Name>
        <City>Washington</City>
        <GraduationYear>2009</GraduationYear>
        <Subjects>
          <Subject>
            <Name>sport</Name>
            <FinalGrade>10</FinalGrade>
            <Keyword>running</Keyword>
            <Year>2</Year>
            <SubjectType>arts</SubjectType>
          </Subject>
          <Subject>
            <Name>informatics</Name>
            <FinalGrade>5</FinalGrade>
            <Keyword>i don't know</Keyword>
            <Year>4</Year>
            <SubjectType>technologic</SubjectType>
          </Subject>
        </Subjects>
      </FormStudy>
    </Education>
    <InformalEducation>
      <Course>
        <Name>chess</Name>
        <YearGraduation>2001</YearGraduation>
      </Course>
    </InformalEducation>
    <Awards>
      <Award>
        <Name>sport competition</Name>
        <TitleAward>first place</TitleAward>
        <YearAward>2008</YearAward>
      </Award>
    </Awards>
    <Memberships>
      <Membership>
        <Title>chess club</Title>
        <MembershipDescription>learn chess</MembershipDescription>
        <MembershipPeriod>2000-2001</MembershipPeriod>
      </Membership>
    </Memberships>
    <Interests>
      <Interest>sport</Interest>
      <Interest>watch tv</Interest>
      <Interest>sleep</Interest>
    </Interests>
    <Jobs>
      <Job>
        <Title>waiter</Title>
        <JobDescription>serve tables</JobDescription>
        <JobPeriod>2010-2012</JobPeriod>
      </Job>
      <Job>
        <Title>mcdonalds</Title>
        <JobDescription>make burgers</JobDescription>
        <JobPeriod>2018-present</JobPeriod>
      </Job>
    </Jobs>
  </Person>
</Persons>
