<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xsl.xsl"?>
<!DOCTYPE Persons [
<!ELEMENT Persons (Person)>
<!ELEMENT Person (Name , Gender , Website , Email , DateOfBirth , Education , InformalEducation , Awards , Memberships , Interests , Jobs)>
<!ATTLIST Person person_id CDATA #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT Website (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT DateOfBirth (#PCDATA)>
<!ELEMENT Education (FormStudy)+>
<!ELEMENT InformalEducation (Course)+>
<!ELEMENT Jobs (Job)+>
<!ELEMENT Awards (Award)+>
<!ELEMENT Memberships (Membership)+>
<!ELEMENT Interests (Interest)+>
<!ELEMENT FormStudy (Name , City , GraduationYear , Subjects)>
<!ATTLIST FormStudy education_id CDATA #REQUIRED>
<!ELEMENT Course (Name , YearGraduation)>
<!ELEMENT Job (Title , JobDescription , JobPeriod)>
<!ELEMENT Award (Name , TitleAward , YearAward)>
<!ELEMENT Membership (Title , MembershipDescription , MembershipPeriod)>
<!ELEMENT Interest (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT GraduationYear (#PCDATA)>
<!ELEMENT Subjects (Subject)+>
<!ELEMENT YearGraduation (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT JobDescription (#PCDATA)>
<!ELEMENT JobPeriod (#PCDATA)>
<!ELEMENT TitleAward (#PCDATA)>
<!ELEMENT YearAward (#PCDATA)>
<!ELEMENT MembershipDescription (#PCDATA)>
<!ELEMENT MembershipPeriod (#PCDATA)>
<!ELEMENT Subject (Name , FinalGrade , Keyword , Year , SubjectType)>
<!ELEMENT FinalGrade (#PCDATA)>
<!ELEMENT Keyword (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT SubjectType (#PCDATA)>
]>
<Persons>
  <Person person_id="1">
    <Name>Kevin Mcall</Name>
    <Gender>male</Gender>
    <Website>kevin.com</Website>
    <Email>kevin@yahoo.com</Email>
    <DateOfBirth>2000-09-07</DateOfBirth>
    <Education>
      <FormStudy education_id="0">
        <Name>NYU</Name>
        <City>New York</City>
        <GraduationYear>2019</GraduationYear>
        <Subjects>
          <Subject>
            <Name>dance</Name>
            <FinalGrade>9</FinalGrade>
            <Keyword>piruete</Keyword>
            <Year>2</Year>
            <SubjectType>arts</SubjectType>
          </Subject>
          <Subject>
            <Name>sing</Name>
            <FinalGrade>10</FinalGrade>
            <Keyword>vocals</Keyword>
            <Year>1</Year>
            <SubjectType>arts</SubjectType>
          </Subject>
          <Subject>
            <Name>english</Name>
            <FinalGrade>9</FinalGrade>
            <Keyword>grammar</Keyword>
            <Year>1</Year>
            <SubjectType>languages</SubjectType>
          </Subject>
        </Subjects>
      </FormStudy>
      <FormStudy education_id="1">
        <Name>High School</Name>
        <City>Washington</City>
        <GraduationYear>2018</GraduationYear>
        <Subjects>
          <Subject>
            <Name>mathematics</Name>
            <FinalGrade>7</FinalGrade>
            <Keyword>sum</Keyword>
            <Year>2016</Year>
            <SubjectType>scientific</SubjectType>
          </Subject>
        </Subjects>
      </FormStudy>
    </Education>
    <InformalEducation>
      <Course>
        <Name>extra dance class</Name>
        <YearGraduation>2015</YearGraduation>
      </Course>
    </InformalEducation>
    <Awards>
      <Award>
        <Name>dance competition</Name>
        <TitleAward>first prize</TitleAward>
        <YearAward>2017</YearAward>
      </Award>
    </Awards>
    <Memberships>
      <Membership>
        <Title>choir club</Title>
        <MembershipDescription>singing in competitions</MembershipDescription>
        <MembershipPeriod>2017-2018</MembershipPeriod>
      </Membership>
      <Membership>
        <Title>science club</Title>
        <MembershipDescription>research</MembershipDescription>
        <MembershipPeriod>2012-2013</MembershipPeriod>
      </Membership>
    </Memberships>
    <Interests>
      <Interest>dance</Interest>
      <Interest>sing</Interest>
      <Interest>read</Interest>
    </Interests>
    <Jobs>
      <Job>
        <Title>mcdonalds</Title>
        <JobDescription>make burgers</JobDescription>
        <JobPeriod>2017-2018</JobPeriod>
      </Job>
    </Jobs>
  </Person>
</Persons>
